let date=new Date()
console.log(date.toString())
console.log(date.toJSON())
console.log(date.toLocaleTimeString())
// IN JS DATE IS OBJECT.MONTH count 0 se start hota hai
let mydate=new Date(2024,6,12,5,20,30)
console.log(mydate.toLocaleString())
let timestamp=Date.now()
console.log(timestamp)
console.log(mydate.getTime())
console.log(Math.floor(Date.now()/1000))
let newdate=new Date()
console.log(newdate.getDay())
console.log(newdate.getMonth())